name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  SPEX_VERSION: 0.31.0

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install spex
        run: npm install -g https://github.com/hekonsek/spex/releases/download/v${{ env.SPEX_VERSION }}/spex-${{ env.SPEX_VERSION }}.tgz

      - name: Validate Spex export
        run: spex validate export
