name: CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install spex
        run: npm install -g https://github.com/hekonsek/spex/releases/download/v0.31.0/spex-0.31.0.tgz

      - name: Validate Spex export
        run: spex validate export
